# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpotsLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



# Allows users to manipulate the spots and update them

from PyQt5 import QtCore, QtWidgets


class Ui_Frame(QtWidgets.QDialog):
    def setupUi(self, spotsLayout):
        self.spotsLayout = spotsLayout

        self.setObjectName("Frame")
        self.resize(1300, 600)

        self.table = QtWidgets.QTableWidget(self)
        self.table.setGeometry(QtCore.QRect(10, 10, 1300, 450))
        self.table.setCornerButtonEnabled(False)
        self.table.setObjectName("tableView")
        self.table.setRowCount(spotsLayout.shape[0])
        self.table.setColumnCount(spotsLayout.shape[1])
        for i in range(spotsLayout.shape[0]):
            for j in range(spotsLayout.shape[1]):
                self.table.setItem(i,j, QtWidgets.QTableWidgetItem(spotsLayout[i,j]))
        self.table.itemChanged.connect(self.itemChangedEvent)


        self.buttonBox = QtWidgets.QDialogButtonBox(self)
        self.buttonBox.setGeometry(QtCore.QRect(400, 550, 400, 40))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.accepted.connect(self.accept)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Spots Layout"))

    def itemChangedEvent(self, item : QtWidgets.QTableWidgetItem):
        previousSpotLabel = self.spotsLayout[item.row(), item.column()]
        self.spotsLayout[item.row(), item.column()] = item.text()
        self.table.itemChanged.disconnect(self.itemChangedEvent)
        for oldSpot in self.table.findItems(previousSpotLabel, QtCore.Qt.MatchExactly):
            self.spotsLayout[oldSpot.row(), oldSpot.column()] = item.text()
            self.table.setItem(oldSpot.row(),oldSpot.column(), QtWidgets.QTableWidgetItem(item.text()))
        self.table.itemChanged.connect(self.itemChangedEvent)

